# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47010a55d2496df3ad0cb989c9b7d378cc4ac058b7563afab68df07c3b2adf51db414554c4aad499f3e766a04ef225ff6050119521ce0e2c81e5cb801cf69361

test:
  secret_key_base: 49bb12f1932604b57dbceb5dca69d433db6ffa65787cbf50f65f35bada575ec95990953ffdcb2989e616f8adc6025f61cf9152b6f58796d47fb1ee1fde60a6ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
